const moduleName = "pf2e-action-support";

const effect_off_guard = "Compendium.pf2e-action-support.action-support.Item.Vh5E1Qgp34sTKfVs";
const effect_off_guard_start_turn = "Compendium.pf2e-action-support.action-support.Item.YsNqG4OocHoErbc9";
const effect_clumsy_start_turn = "Compendium.pf2e-action-support.action-support.Item.lsICo0LAyrWy2cDm";
const effect_enfeebled1_start_turn = "Compendium.pf2e-action-support.action-support.Item.9QvJm6xIKWjti3PD";
const effect_paralyzed_next_turn = "Compendium.pf2e-action-support.action-support.Item.aLqCfr4Yl6g2eyoO";
const effect_enfeebled2_start_turn = "Compendium.pf2e-action-support.action-support.Item.66Sg7uVVaIb3tOib";
const effect_immobilized1_round = "Compendium.pf2e-action-support.action-support.Item.FCKm1dZKZzF7Jkxl";
const effect_blinded1_round = "Compendium.pf2e-action-support.action-support.Item.KmUCaFZSk9efn9AR";
const effect_dazzled1_round = "Compendium.pf2e-action-support.action-support.Item.1u4ZAmfeWKyN3uKK";
const effect_slowed1_round = "Compendium.pf2e-action-support.action-support.Item.xTHKw0VHuqu6SI93";
const effect_deafened_round = "Compendium.pf2e-action-support.action-support.Item.7roTkQ4QHWDWZkJM";
const effect_deafened_minute = "Compendium.pf2e-action-support.action-support.Item.enKjIoLFr4T0gfEe";
const effect_deafened_hour = "Compendium.pf2e-action-support.action-support.Item.KnjwOiVZr5Twwoum";
const effect_skunk_bomb_fail = "Compendium.pf2e-action-support.action-support.Item.Ed57eZ72j6RGAIp4";
const effect_skunk_bomb_cfail = "Compendium.pf2e-action-support.action-support.Item.0v7THqjruKWI0wJ4";
const effect_battle_medicine_immunity_hour = "Compendium.pf2e-action-support.action-support.Item.GMb4x4eHVGD9Tfzp";
const effect_treat_wounds_immunity_minutes = "Compendium.pf2e-action-support.action-support.Item.b1ILZ8YQvBd9XA2b";
const effect_demoralize_immunity_minutes = "Compendium.pf2e-action-support.action-support.Item.DFLW2gzu0PGeX6zu";
const effect_concealed_start_turn = "Compendium.pf2e-action-support.action-support.Item.1KroJZ72a4Hc10fW";
const effect_restrained_end_attacker_next_turn = "Compendium.pf2e-action-support.action-support.Item.zol83j7l2cBSmY3a";
const effect_grabbed_end_attacker_next_turn = "Compendium.pf2e-action-support.action-support.Item.5MNn6cmXxbORB8x8";
const effect_panache = "Compendium.pf2e.feat-effects.Item.uBJsxCzNhje8m8jj";
const effect_disarm_success = "Compendium.pf2e.equipment-effects.Item.z3ATL8DcRVrT0Uzt";
const effect_adverse_subsist_situation = "Compendium.pf2e.other-effects.Item.wHWWHkjDXmJl4Ia6";
const effect_conduct_energy = "Compendium.pf2e.equipment-effects.Item.lU8IO9FIGK1DXVMy";
const effect_daydream_trance = "Compendium.pf2e.feat-effects.Item.RATDyLyxXN3qmOas";
const effect_energy_shot = "Compendium.pf2e.feat-effects.Item.zocU4IYIlWwRKUuE";
const effect_entitys_resurgence = "Compendium.pf2e.feat-effects.Item.yr5ey5qC8dXH749T";
const effect_follow_the_expert = "Compendium.pf2e.other-effects.Item.VCSpuc3Tf3XWMkd3";
const effect_feint_success = "Compendium.pf2e-action-support.action-support.Item.P6DGk2h38xE8O0pw";
const effect_feint_critical_success = "Compendium.pf2e-action-support.action-support.Item.lwcyhD03jVchmPGm";
const effect_feint_success_attacker_target = "Compendium.pf2e-action-support.action-support.Item.XcJAldj3qsmLKjSL";
const effect_feint_crit_success_attacker_target = "Compendium.pf2e-action-support.action-support.Item.jfn0eHEAnoxNI7YS";
const effect_bend_time = "Compendium.pf2e-action-support.action-support.Item.w4iqlhWrlHLlOiYP";
const effect_jinx_immunity = "Compendium.pf2e-action-support.action-support.Item.DGGVvtjm7r8yhSKG";
const effect_jinx_clumsy1 = "Compendium.pf2e-action-support.action-support.Item.aEhh2kWTcKJacdHe";
const effect_jinx_clumsy2 = "Compendium.pf2e-action-support.action-support.Item.MkWyAtPU3CAFpgdQ";
const effect_aberrant_whispers_immunity = "Compendium.pf2e-action-support.action-support.Item.zt5GIv9435SF0fYn";
const effect_intimidating_strike = "Compendium.pf2e-action-support.action-support.Item.w9i0aY2IQ3jvCX9K";
const effect_reach_spell = "Compendium.pf2e-action-support.action-support.Item.jLxv3W9FgO2SbxVC";
const effect_spectral_hand = "Compendium.pf2e-action-support.action-support.Item.wArBvC6i6Das3r8I";
const effect_hunt_prey = "Compendium.pf2e-action-support.action-support.Item.a51AN6VfpW9b4ttm";
const effect_allegro = "Compendium.pf2e-action-support.action-support.Item.kZmteGRpdP6qgIdC";


const afflictionMap = {
    "Abysium Powder DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.yCcMSn9TE1NfzBbE",
    "Abyssal Plague DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.9gRcGRV5fBdi34s7",
    "Abyssal Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ev3SITzCySknbkjF",
    "Achaekek's Kiss DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.grSlUGKyRhRoekMR",
    "Addictive Exhaustion DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ecHne25ZfJhUlu3m",
    "Addlebrain DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ER29qj5CBz7ET6P2",
    "Adolescent Sea Serpent Algae DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mAw6VkW6Q1lpg3lH",
    "Alcohol DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.xDCrZs790Liytu3S",
    "Alghollthu Lash DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.rQNRAy6WCODHV4WK",
    "Alluring Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.yrqqE0df892aU9Ok",
    "Amnesia Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.yEVmRzhnvbjSIXB0",
    "Amphisbaena Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.N6fU9obdAYvTueig",
    "Anadi Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.sGKx6NBDpRY8ZD3O",
    "Antipode Oil (Fire) DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vbDOVWBjW9kMYNVL",
    "Antipode Oil (Cold) DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vbDOVWBjW9kMYNVL",
    "Arsenic DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.pqegKPXhVq0LbL57",
    "Ash Web Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zpDlUFhVfWsYZ1xy",
    "Aspect of Hunger Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Oo9zzXKCyW5oNB70",
    "Astringent Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.PFN8cE6QiZ7oM1sw",
    "Athach Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ynCYxnQWD47ZFp59",
    "Atrophic Plague DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.cUF7fPbqFzgAenl7",
    "Avernal Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.pR2MdnDq4hy3toNs",
    "Azure Lily Pollen DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3gDPvAP7H03mSo7Z",
    "Azure Worm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.jwIM5zO96uI5yzjO",
    "Baneback Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.B7P1hgqC96QIadvy",
    "Barbtongued Wyvern Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Ty7mtRVNRvJjYDhV",
    "Barrow Quasit Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.RM3ocTvVCtdVpeYU",
    "Basidirond Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.nsj7HnNPgP8nHseM",
    "Belladonna DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Q30U5sVfScvCJ8Rr",
    "Betrayal Toxin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.b21rTH02dvEkVikE",
    "Bitter Heart DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.NyHn0WPyD7Ue9yfO",
    "Black Adder Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zZOu7ONIyH3mpdEL",
    "Black Apoxia DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.w5cAPUnVB4H6yowV",
    "Black Ink Delirium DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.s7kBb1T57ZjEzvFP",
    "Black Lotus Extract DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IXdsf7hCOENo8zsk",
    "Black Scorpion Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.RFln6ZlshpcuZ9Dt",
    "Black Smear Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.5E3MeG9ti1x7rFIm",
    "Blackfinger Blight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.pCbyTksK3vMUtaRy",
    "Blackfrost DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4vJN4ULBzY0DezWJ",
    "Blackfrost Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.AgZhTjm1x99kESU5",
    "Blaze DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.U6zoLjsdXrUqbRSq",
    "Blightburn Blast DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.jdepjecaLS89FBug",
    "Blightburn Resin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.9NTdh0tGoJpeVJXF",
    "Blightburn Sickness DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.kqnaYlgAAMGUVUiv",
    "Blinding Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.lT7Hq4fEnIMHrTn9",
    "Blinding Sickness DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CttvE8DIjIPHTRKa",
    "Blisterwort DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.EHLJU80FA2PLUDSX",
    "Blood Sap DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.RxI0VQkP4ar5qW2r",
    "Bloodeye Coffee DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.y5pfb3z64f0dmg7f",
    "Bloodfire Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ybFFsCR8mDl2Lpp9",
    "Bloom Curse DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.MrcHDzn3z8bZC9KF",
    "Bloom Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.e6MHQOHOTFXbHcQi",
    "Blue Dragonfly Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.dEgYePF9hJhmKyvG",
    "Blue-Ringed Octopus Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.XbrlqdzRMtyic6D9",
    "Bog Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.F3HO3xaokQHe2kzU",
    "Boiling Blood DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.gqgoEwB6b2CZNbOc",
    "Brain Collector Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.J6b0NEwSwZVAtvP2",
    "Brain Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oqTorFA3LcPwwadI",
    "Breathtaking Vapor DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Q4QFKhfUKsob79Eb",
    "Brightshade DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.amTKUGHTsdrzKYda",
    "Brimstone Fumes DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.OoUnoLIyajAmJ0II",
    "Brood Leech Swarm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.cY037sJFhkEmJKNK",
    "Bruorsivi Sap Infusion DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.WvsP1wBZDND09Yne",
    "Bubble Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.UNY5Z1jyBT2upz9F",
    "Bubonic Plague DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.7T5ctImwJnOalRUh",
    "Burning Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0JIbTqzew8I0LgeH",
    "Burrowing Viper Rat Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.M4NQ5ZYV7aDbcqXp",
    "Butterfly's Breath DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bn9yVLRuS8H1PUcv",
    "Cacodaemonia DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.XheMaD6NV3UuGfNX",
    "Cairn Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Lm7jYgGTeqATzhx4",
    "Careless Delight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.OhFGBFec6G3UHsqC",
    "Carrion Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.aZ3q5yMxhz1L0LOu",
    "Caustic Monitor Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.fPvFFmx8ecLAm9mg",
    "Caustic Nightmare Vapor DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ivpTvHRYsUxXjRq4",
    "Cave Scorpion Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.hbfGM1Le43FtE4Qc",
    "Centipede Swarm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Eh0xVQTreqmo0ENZ",
    "Cerulean Scourge DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.O35m2p2ZhIqNq4cb",
    "Chew Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.hwjxtTN4dodlaU58",
    "Choleric Contagion DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.NfI5Mhk3ePGZYVph",
    "Cladis Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.JtG6WTR0T9Y2lqlG",
    "Clown Monarch DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vzHPP6XBI7NCFx2R",
    "Clubhead Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.2fRrAzQfiG8LDwck",
    "Cocytan Filth DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.AXZV7mqnH5K1HU4Y",
    "Cold Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ohcaXE8PSRrDS2VB",
    "Compsognathus Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.krfarLyYSmSH0dlR",
    "Concentrated Xulgath Bile DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.02eiMvtumcmwTmtv",
    "Crag Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.u4Z9c3S4uAA6frXG",
    "Crawfish Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.hJgL0Hj3twbhAKNu",
    "Crimson Worm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.JBcInuhUkFArkV6G",
    "Crystal Corruption DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.KqQgMuDWXJMT8BWL",
    "Crystalline Corruption DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Yg2IrzVjIEXweYv7",
    "Curare DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.wREyfwGuH51JfHIb",
    "Curse of Death DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.YkE0mfzhzL5W3pqs",
    "Cytillesh DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0joddSy5q1sf659j",
    "Cytillesh Oil DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4gzixzUeUCdL8hIS",
    "Daemonic Famine DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.L0DT5OY7HScRuhiB",
    "Daemonic Pestilence DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ztUOkr2IwSU7chP9",
    "Dancing Lamentation DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.PjQ7owIMNdrAAHaM",
    "Dark Naga Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.gO3c9baFvzcz7KUa",
    "Daylight Vapor DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.fjhVpI8RiS1OsEmv",
    "Deadly Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0UsJtZJGr7u4HQo1",
    "Death Drider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0tCvo3WHydFtyRyy",
    "Deathcap Powder DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Hx6BNzdMKYzS7Aml",
    "Demonplague DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.GxG8rxWN6J4Vhhed",
    "Dezullon Fountain DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.UKtVF0vtvP3wmZG1",
    "Diluted Hype DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.W0B467PCdn7JApQ6",
    "Dipteric Dread DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.2xQF3sMqrdCVwOYX",
    "Divine Plagues DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.YXEo7IlprPKxrNzS",
    "Doru Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.kPwzbcv4jJjY6mVb",
    "Dragon Bile DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.cTbU5YiwBBQCKoqh",
    "Draining Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.xbDHg8QQBTnUuCBH",
    "Dream Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.I4CmarwZc88I0kzz",
    "Dreamtime Tea DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.m2Wmqy8C0hf2dJoG",
    "Drider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3wFzenj89ZR68pnN",
    "Eldritch Flare DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.haNqREcJR0apTZrL",
    "Elven Absinthe DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.awXCdbYpgtce55Kd",
    "Emperor Cobra Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.8iIstPTjeSQVWUkU",
    "Endless Nightmare DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.G8nViWwUzqkORNkb",
    "Enhanced Hunting Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.6vDxboqA1ceo2CSJ",
    "Ether Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.TMOvwqQlPSZCP0Nj",
    "Eurypterid Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CLplEQdSQpqcaYL9",
    "Expeditious Evolution DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.p4QxRt2TpaglXUCZ",
    "False Death DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.m7BrxqAkDLPbwx5W",
    "False Hope DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CxNtWF4BRymTdjUK",
    "Fearweed DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SBkJsSbwzLSJWs4P",
    "Fermented Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.l4nH0V9KPQMhdyek",
    "Ferrugon Tetanus DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bIKizlEs7dkPgNsW",
    "Fill Lungs DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.wF31eI3BVMLwm3fT",
    "Filth Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.YitPYJ72yr7Mjtwp",
    "Fire Jackal Saliva DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.v6Ml5PcHj26KNs4b",
    "Fire Jelly Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Qejfplqss3uiYIPr",
    "Fjord Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.nBmiahJgobhTeKmS",
    "Flask of Whiskey DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.lJTuVxGnZuZwrooJ",
    "Flayleaf DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.5fPuE65AVUmyBAHG",
    "Flea Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Ko1y0nl6d0jSsn56",
    "Fleshgout DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.UD5JjtiP8iKp7bdU",
    "Flesset Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.FUnHb81UuLBYzqpM",
    "Fly Pox DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bojK17BaKXs3tUYw",
    "Flytrap Toxin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.j4Ns9qk8AIJSqGZn",
    "Foodborn Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.BbAqpc3doECR7mWl",
    "Forgetful Drops DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.hLl9aKFFy2OEJU3u",
    "Forgetful Ink DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3HZb3NrfqxfbZTLn",
    "Formian Trench Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ITZXAVHPkAOuDS7B",
    "Frenzy Oil DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.dZyyZp3VFeW5uR79",
    "Frozen Nightmare DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.TAE0NQOEzGt8nIZM",
    "Ghast Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.qB60tzTpIUBlOC08",
    "Ghost Crystal Cloud DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.RcNUPotMhiNgtQC5",
    "Ghoul Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.cA3HX5HisHuBFyuX",
    "Giant Ant Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IdSkqzONoiRuqJrR",
    "Giant Centipede Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.aXQg8QQkk3EdCfXx",
    "Giant Octopus Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.uTkStM0YajHY5y9L",
    "Giant Scorpion Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.1HCdMLclN3iFfEQB",
    "Giant Tarantula Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.XbopO94gIsvz2xQ7",
    "Giant Toad Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.tztTEq8715Lt0Loy",
    "Giant Trapdoor Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CQkGCsYuvMZRbYb7",
    "Giant Viper Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.R7pswmu86XzfMcX7",
    "Giant Wasp Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.D2TEuEZpWqeNF1IC",
    "Girtablilu Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IK5pGJbwk7xjcruz",
    "Goblin Pox DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.dvuiG9IugyTRgrgg",
    "Gold Defender Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.m7oy24wR5J2uhgeb",
    "Goliath Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mA5bo1TptRdwRxgb",
    "Gorgon's Breath DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mE6cx1z0hDYLLsEt",
    "Grave Blight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vk8AEbT3P2Txgl1g",
    "Graveknight's Curse DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.DvluplZGzMVbaWyw",
    "Graveroot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0xokszEphFO7S0A8",
    "Grey Mold DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.KhC8ga7YUFZYkL5W",
    "Grimstalker Sap DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.AwcOHdj6gZOxDCv5",
    "Grioth Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mgXuzY9uOZYKmdu3",
    "Grolna DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Jf7JIzMJlWekbQT5",
    "Guardian Naga Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SwGSnDaCZjVJ8URW",
    "Guillotine Golem Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ndI08MJALHb0B5aY",
    "Hadi Pestilence DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.gWPxyL17Qh8hJNXS",
    "Harvester Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.TQhb2JdfEmTmW5rd",
    "Hellwasp Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.QAvbdZDjpvXYfXWj",
    "Hemlock DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3wwsHGX2ssBDQxNS",
    "Homunculus Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.7Ss8IjEqybZ2zItO",
    "Honeyscent DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.B2NXDoEvN6YuEDMv",
    "Hooktongue Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vHMDjyx1UzaCb16o",
    "Hunger Oil DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vTg3YkBuLkAnqCKQ",
    "Hunting Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iXqNIgEEzTMlT5K0",
    "Hyldarf's Fang DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.6g2rT4dHPwkfJpUL",
    "Hype DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.NJrX4l4U4vSnsapd",
    "I Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Kd5y7TWQyQPxmW7d",
    "Ice Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.9h329NgOPtLvo7Gk",
    "Immense Mandragora Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.PrdG3Rz1PHwTJIaR",
    "Imp Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.EARJuvoAAN6gJbdd",
    "Imp Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.yNiGoo8VadjGpr7Y",
    "Incite Insurrection DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bTu74PPfzgaxsv9w",
    "Infused Wyvern Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.swvmjDoOfYSwBVfY",
    "Insidious Mummy Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.OqePwY4h9Q6e7TlZ",
    "Internal Insurrection DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.qGp2qV9cev0NbETA",
    "Invasive Blackfrost DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SkcKN4hgycjvx6PG",
    "Iron Golem Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.gMaaJeo4NKKiOfdP",
    "Isolation Draught DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.dd3Rz9JsJnrkw1HI",
    "Isqulugia DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.uv4XUQwimS2ZyIhs",
    "Itchy Rash DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.xUbmYQ6qcvnJJZdA",
    "Jaws DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.WbmmkoF2CvrSCB7c",
    "Jellyfish Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Y9eNAISyWoVlze7B",
    "Joro Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.I5CJsNoV5juI7wPb",
    "Jorogumo Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3SRSDqFKkLmvXYjQ",
    "Jungle Drake Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.cbsU9gRdpsoXM8xi",
    "Karumzek Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.w0Qt8VdmRC5e6EK9",
    "King's Sleep DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.YR0szN8xXl9R13kp",
    "Kithangian Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Za2HQ9dpiJ6PIWNv",
    "Knockout Dram DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.U4ifHMg0UMgavfQo",
    "Kraken Ink DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bTQd5upv2IKLCzAF",
    "Lamashtu's Bloom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ETtAuvOSlHY9rSCP",
    "Leadenleg DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Yp7YFoh8i2L2Us5a",
    "Leng Ghoul Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.I2Q2VbVuJQgvUr89",
    "Leng Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.7PhEB4s8UKtBbnek",
    "Leng Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.U7UaPunMKXulWdze",
    "Lesser Mummy Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.OpWuQQVobeUFUe80",
    "Lethargy Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Q1meC5y9UqMVueKe",
    "Liar's Demise DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.NIpofpQJsFUvKx4s",
    "Lich Dust DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4ap1pNAOk2Odk90F",
    "Lifeblight Residue DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.k6xNaVzjk6eaGwwg",
    "Linnorm Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.hiPz9rJ8d66wIshs",
    "Lionfish Spear DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.8MWxbhHIaQxdkCDY",
    "Lizard Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ZqzNjIrhuzyQhcPl",
    "Looter's Lethargy DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.YKXcc44yBoIrX4Du",
    "Lusca Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zRUTqpkZImj5feqp",
    "Mage Bane DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.f9AREo51zCmLNWLU",
    "Magma Scorpion Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.QTSRSDFIraDSWbyA",
    "Malyass Root Paste DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vY0ftZvbj3H4ZVOd",
    "Mana Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IIVXLl6YfSa6ApX8",
    "Mandragora Swarm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.536YYOCuTA4OEzHE",
    "Mandragora Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.diKpQ7PI6sfsVR96",
    "Many-Eyed Blight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.n0nfQjDIQJ4zOOY6",
    "Marrow Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CajyS3O7fMT9EG8c",
    "Megalania Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ofnFHz2nxhQMVd2Z",
    "Mind-Rotting Toxin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.HektHmXsJc9L4h8D",
    "Mindfog Mist DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.wgOMvj7L5w5SlVkY",
    "Mindmurk Oil DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.9TiaKb6MEKcjXMLc",
    "Mix Couatl Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SmLpg0FygVod5Kba",
    "Monitor Lizard Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.I7aklW5COnfcfUcw",
    "Monstrous Yeast DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.87BNcuyJKRGUIIfS",
    "Mosquito Blight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.nzE6HkKOoYPdv190",
    "Mummy Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.BT3F9Pzt5JOD1EGx",
    "Mustard Powder DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.N4yIHrYmnIPQm8ED",
    "Nagaji Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Opk4Vgs2eppFSEzT",
    "Najra Lizard Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.XcA6jQZHcdnzVb9S",
    "Nasty Ink DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.7bZ1WnJsZH2GiAER",
    "Necrotic Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.9BCrjGKURUvP92H4",
    "Nettleweed Residue DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.aKHgzyRVoOl6gdrs",
    "Nightmare Salt DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.tHwMECQMWbTm3KD1",
    "Nightmare Vapor DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.2L7ZkMYhpGReN1Ah",
    "Oblivion Essence DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oZgI1X2FOLufxIrF",
    "Ogre Spider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0uURhpSUxlIHyrFk",
    "Oil Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.T3YVyM0PwROZM0je",
    "Old Giant Wasp Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IJoM84oeikvUnj6x",
    "Osyluth Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.cfqP408pI5P8vA5p",
    "Pale Fade DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.6kiLT0Gm5jdGlpiv",
    "Pallid Plague DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.jWeXHPDvaouXnupd",
    "Paralytic Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0RWCEh3cDikbxWl2",
    "Paralyzing Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.EVZAPmtWUX7FzlzD",
    "Peluda Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3EVpbuhWI5cE9ci1",
    "Penanggalan Bile DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.pbRwhOAfhSLlwOR8",
    "Pesticide DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.J6kZQRk9gpj67K5w",
    "Pestilential Aura DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.56qB99L60pWD0YoD",
    "Phantasmagoric Fog DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Zj1gZxRGlaPk4gSc",
    "Phantom Mold Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.LuXfKQg4BTJjc2gr",
    "Phomandala's Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.z6Y04IkCcxaE70tS",
    "Piscovenom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.QHsGCmj7abYi3uCW",
    "Pit Fiend Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.7oW4srrQBkXWl3xE",
    "Plague of Ancients DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CQgLbyIXBcFNCBam",
    "Plasma Hype DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.uIVRErLu92hoJb8r",
    "Poison Ink DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.BgSqr3oTVMhuTOQc",
    "Poison Sedum DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mggGGZu1zRKVlyM4",
    "Pollution Infusion DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.nDwcWrpB3HuByXPx",
    "Pufferfish Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iCtWeKhR4rdzg3ij",
    "Pukwudgie Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.KZngbOadwOel7j3V",
    "Pummel-Growth Toxin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.aFbTUZxLx1iqqQuu",
    "Purple Pox DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iOj9CNhcoKmtTWuv",
    "Purple Worm Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.emGT6BItjXf5BLpB",
    "Purple Worm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ydNsuJbu8dSy7Jz6",
    "Pyrexic Malaria DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SfNCxf219qglG4MN",
    "Quasit Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.U8GkpZrDIjKDu4UF",
    "Quetz Couatl Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.rGxqG7CPhxw507gh",
    "Rabies DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zyf1FqgKhEiV91fU",
    "Raktavarna Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.nUar0mAQx9M5HxTj",
    "Rancid Bloat DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iXW1fvMw6dIurHzW",
    "Rapid Lead Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.grkfiRhlfERbFXCp",
    "Ravenous Giant Centipede Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CAyWIQCDoI5mOq7N",
    "Red Ant Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4GkBExhyS8stnSVv",
    "Reef Octopus Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.DlPC1Y4C2VFPSnGs",
    "Reefclaw Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.0Tu8cvCtNLlmRp51",
    "Refined Pesh DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.NnXkapl9moblszhE",
    "Regenerative Blood DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.EK20h8e6dJK2kcic",
    "Rompo Chills DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.JHqUVbm8fun13v0g",
    "Rotting Curse DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oLesEDZKp4ftSyjr",
    "Rupturing Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.up8dE4yU9dw1gL0J",
    "Rusty Chains DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.KQzAQ5tDGZxOVIiB",
    "Saboteur's Friend DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oHs3v4yxlq804Rxb",
    "Sand Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mlkwqBYEoXKjg3np",
    "Sard Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.XwShJfJOuiK3Lczv",
    "Sarglagon Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.gt3GqPeGcuVu3dMk",
    "Scalathrax Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3ojMXtrTzQt5Lscy",
    "Scarlet Mist DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iAQbZNQruf4F4zDZ",
    "Scorpion Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zimxclsBxmfaPNdc",
    "Scour DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.GNt5Ibekpc9FB7Cz",
    "Sea Serpent Algae DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zxcNZqLC7hKGCt9F",
    "Sea Snake Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mFoQNYAi1FTx8Ig7",
    "Septic Malaria DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.EkJCiJF8eoZl0qWA",
    "Serpent Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.R4Qnp6RSBMmz4agp",
    "Serpentfolk Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.CX8koZy7avXyAWfN",
    "Seugathi Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.y6cYcxvSJYWkPkKx",
    "Sewer Haze DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.njMDZ5d8YHfQILBz",
    "Shadewither Key DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.OOBIve2q5rVtXcks",
    "Shadow Essence DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.sqckD7nrAsPY39Z4",
    "Shiver DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.JrjpalDUpfjKvy6F",
    "Shoal Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.MRMd4TcqE8lTRrgy",
    "Shrew Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IIGGt6vEMLOx0ibs",
    "Shuln Saliva DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.KYQTGW5n7HzAvfU2",
    "Sight-Theft Grit DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ZyXQy9GeiOj76ld4",
    "Skitterstitch Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.I2NF4Qa4OmeT4oIT",
    "Skrik Nettle Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.w4MDycpnhnBTjc1q",
    "Skull Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.nCvYfEWTB4rHQOfe",
    "Sleeping Gas DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.TBGP58ZyzNPTXS5S",
    "Sleeping Sickness DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SISZQOmrWe8XIAOg",
    "Slime DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.tCONoOegED0lGAo2",
    "Slime Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bK13gweSPRudBV0p",
    "Sloughing Toxin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.7XNlgOFICuqhQy4i",
    "Slumber Wine DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.i02GPFWw2N1EmNiq",
    "Smokeside Sour DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oeRyg7PyTQuG0O4r",
    "Smother Shroud DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.1B4uXLcLaV2Ku25q",
    "Snapdrake Pollen DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.osFH4bUGU3WFSZBK",
    "Spear Frog Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.lMCQZDeHcg2Rwl2L",
    "Spear Frog Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.3w5moe1GAxpHJglx",
    "Spectral Nightshade DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.HDntYO05V5YyUfqT",
    "Spell-Eating Pitch DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.o4s2oRBIfoSHFYHj",
    "Spider Mold DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.syePdSHG9kvGN2xh",
    "Spider Root DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.8kV4M9lrmYWbqWGh",
    "Spider Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.WTBUyCo2sRwhXroc",
    "Spider Swarm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.y8meAQPHVYOc86cs",
    "Spiny Eurypterid Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vzYyB0m0GNR9exTm",
    "Spirit Naga Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.QoIkMMeGs32VQTcq",
    "Spore Blight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.HPRTvgJmXXuJSJmp",
    "Stabbing Beast Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zfy9cXjXLpzF4VNh",
    "Stingray Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.B7B3MUA055FC3bzR",
    "Stupor Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iUW6Mnmz2aEyzUcN",
    "Sulfur Poisoning DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.izdtUiEVZ7r7ZNZ4",
    "Swarming Wasp Stings DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.frwh9ctRSgrwwrYu",
    "Taiga Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.2bVg2MqCsdKXCUdn",
    "Tangle Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.pQPT02NAJVPo7ucA",
    "Tarn Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.JK27zoOnq6l1oJn5",
    "Taster's Folly DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.hbXlgWs7tfoFasKJ",
    "Tears of Death DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.XKTcbyFDMj5MarCl",
    "Tendriculos Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iUQnJwayQ85D9Npi",
    "Terinav Root Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.VFc6jeJt80izrxuJ",
    "Terminate Bloodline DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Fhste6ldzrJNp0Nm",
    "Terror Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.uM9rKzgTzqG3DIeP",
    "Tetanus DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4OGsbJtOZPTP9da6",
    "Thulgant Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.iuaqSVrrApFFteFP",
    "Tick Fever DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.yaRIItzRNJrjpNQf",
    "Titan Centipede Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.IgIexXxfA30jqluf",
    "Titanic Flytrap Toxin DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.vtZmpkJ9dd2YlOMW",
    "Toad Tears DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.8XLxvMnho0iIVOCT",
    "Tor Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.b4kXzhaTzd9RVUQq",
    "Toxic Effluence DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.x0xV0tPAt9PiUhWO",
    "Undead Virulence DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.LJHV9hlqVt9BeVe0",
    "Urveth Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.LvRTjUmO4R035fTg",
    "Vampire Drider Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.H3jlEfyPeEhPMdv7",
    "Vargouille Transformation DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.Jua2ePI1jQqYPNK4",
    "Vargouille Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.VTnB8if9aAw7rZUn",
    "Vargouille's Kiss DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.P7dmRKV0q5H5tSb0",
    "Violet Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.zNk9yrc5COlx4nyp",
    "Violet Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ayTQ8imKBY5w6rax",
    "Viper Swarm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.QXTENmcqjj6xV7Ha",
    "Viper Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.ah7HAqGmDLBOeyCy",
    "Vishkanyan Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.xvnvcRj8c0Nq8N06",
    "Void Death DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.pHvxFRtvZPl0Y6rG",
    "Warpwobble Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.mjwcfk6xEewdJlYr",
    "Wasp Larva DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.jFd6IHTVBjbFwU9V",
    "Wasp Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4ggioPFgzZx5emlr",
    "Web Lurker Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.HhIUrODqf6SsUHtJ",
    "Weeping Midnight DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.BKLngufD8FpmrsJW",
    "Wendigo Torment DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.20rI4pam0r5Mu1JF",
    "Weredigo Torment DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.diM3iQyjLei9FIBL",
    "Whiptail Centipede Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.TDczcCWsM92BRk3M",
    "Whiskey DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.X0uzA4FLrXu2rq2K",
    "White Serpent Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.bVGqCOjDUu1OQ62W",
    "Wolfsbane DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.AOftoGhA5VJbfo53",
    "Wretched Weeps DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.MnxTf41RO0zC8iqT",
    "Wyvern Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.p4bgKxLKIF4Y9UQI",
    "Wyvern Poison [Applied to 4 Bolts] DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.4V6ibRX3pgHGCNH3",
    "Wyvern Sting DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.2Q6RBnmSoPFeMV6q",
    "Wyvern Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.i7T4i9zinklSpdhA",
    "Xill Eggs DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.LKz73UIJJ6K2gsqg",
    "Xiuh Couatl Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.SHDgz0I5pUroaM8g",
    "Xulgath Bile DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.5ArkA4oz7jXX6vE8",
    "Yamaraj Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.WEKGu58rBmlBAli9",
    "Yellow Mold Spores DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.QZqPrEA8tnCf5vfu",
    "Yellow Musk Poison DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oMCSsh2g9EjGXtZY",
    "Young Linnorm Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.EPllsOfWFYi5aySU",
    "Young Sea Serpent Algae DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.BkBAHiBywgngZtW9",
    "Zerk DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.NMndKdzXgEkaCjZG",
    "Zinba Venom DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.oRrLpzArMYKUCwaV",
    "Zombie Rot DC": "Compendium.pf2e-action-support.action-support-afflictions.Item.PIOxJwNMfelZ9Me4",
}

const pol = ["spell-effect-wild-morph", "spell-effect-juvenile-companion",
"spell-effect-pest-form", "spell-effect-wild-shape", "spell-effect-enlarge", "spell-effect-enlarge-heightened-4th",
 "spell-effect-shrink", "spell-effect-summoners-visage", "spell-effect-ooze-form-ochre-jelly", "spell-effect-elephant-form",
 "spell-effect-gaseous-form", "spell-effect-swarm-form", "spell-effect-unusual-anatomy",
 "spell-effect-righteous-might", "spell-effect-corrosive-body", "spell-effect-corrosive-body-heightened-9th",
 "spell-effect-cosmic-form-moon", "spell-effect-cosmic-form-sun", "spell-effect-fiery-body",
 "spell-effect-fiery-body-9th-level", "spell-effect-ki-form", "spell-effect-apex-companion",
 "spell-effect-nature-incarnate-kaiju", "spell-effect-nature-incarnate-green-man", "spell-effect-dragon-claws",
 "spell-effect-evolution-surge", "spell-effect-gluttons-jaw", "spell-effect-embrace-the-pit", "spell-effect-moon-frenzy",
 "spell-effect-divine-vessel", "spell-effect-divine-vessel-9th-level"];

const polAnim = ["spell-effect-aberrant-form-", "spell-effect-animal-form-", "spell-effect-insect-form-",
"spell-effect-ooze-form-", "spell-effect-aerial-form-", "spell-effect-bestial-curse-", "spell-effect-dinosaur-form-",
"spell-effect-fey-form-", "spell-effect-elemental-form-", "spell-effect-plant-form-", "spell-effect-daemon-form-",
"spell-effect-devil-form-", "spell-effect-dragon-form-", "spell-effect-tempest-form-", "spell-effect-angel-form-",
"spell-effect-monstrosity-form-", "spell-effect-element-embodied-",
"spell-effect-animal-feature-", "spell-effect-adapt-self-", "spell-effect-shifting-form-", "spell-effect-dragon-wings-",
"spell-effect-mantle-of-the-frozen-heart-", "spell-effect-mantle-of-the-magma-heart-"]

const dcByLevel = new Map([
    [-1, 13],
    [0, 14],
    [1, 15],
    [2, 16],
    [3, 18],
    [4, 19],
    [5, 20],
    [6, 22],
    [7, 23],
    [8, 24],
    [9, 26],
    [10, 27],
    [11, 28],
    [12, 30],
    [13, 31],
    [14, 32],
    [15, 34],
    [16, 35],
    [17, 36],
    [18, 38],
    [19, 39],
    [20, 40],
    [21, 42],
    [22, 44],
    [23, 46],
    [24, 48],
    [25, 50],
]);

const DURATION_UNITS = {
    rounds: 6,
    minutes: 60,
    hours: 3600,
    days: 86400,
};
